apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: sovernut/kub-demo-task:latest
          env:
            - name: AUTH_ADDRESS
              # value: "10.101.135.143"
              value: "auth-service.default"